---
- name: Upgrade Device Edge
  hosts: edge_servers

  tasks:
  - name: Check Status
    shell: rpm-ostree status
    register: status_out

  - debug: status_out

  - name: Check Upgrade
    shell: rpm-ostree upgrade --check

  - name: Upgrade
    shell: rpm-ostree upgrade

  - name: Check Status
    shell: rpm-ostree status

  - name: Reboot
    shell: systemctl reboot
