---
- name: Upgrade Device Edge
  hosts: edge_servers

  tasks:
  - name: Check Status
    shell: rpm-ostree status
    register: status_out

  - debug: var=status_out

  - name: Upgrade the rpm-ostree image allowing downgrades
    ansible.posix.rpm_ostree_upgrade:
      allow_downgrade: true

  - name: Check Status
    shell: rpm-ostree status
    register: status_out

  - debug: var=status_out

  - name: Reboot
    ansible.builtin.reboot:
